---
title: "EDA: Maximzing WOBA with Launch Angle and Exit Velocity"
author: "Sarah Sult, Brooke Coneeny, Erin Franke"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(base_color = "#cc002b")
```

# Motivation

- Two of the most popular stats in the MLB have recently been launch angle and exit velocity 
  - We wondered: can we prescribe a woba maximizing launch angle for an individual player 
  based on their power profile?
```{r, include=FALSE}
library(baseballr)
library(tidyverse)
batter_all_2020 <- read_rds("../private_data/all2020data.rds")
batter_all_2019 <- read_rds("../private_data/all2019data.rds")
batter_all_2021 <- read_rds("../private_data/all2021data.rds")
batter_all <- rbind(batter_all_2019, batter_all_2020, batter_all_2021)

#get all balls in play  
in_play <- batter_all %>%
  filter(description == "hit_into_play") %>%
  select(launch_angle, woba_value, player_name, launch_speed) 

#max EV per player and combine with balls in play (so there is a column categorizing the player who 
  #hit the ball by their max EV in the season)
max_EV_grouped2 <- batter_all %>%
  group_by(player_name) %>%
  summarize(max_EV = max(launch_speed, na.rm = TRUE)) %>%
  filter(max_EV < 200 & max_EV>0) %>%
  right_join(in_play, by = c("player_name")) %>%
  mutate(EV_group = cut(max_EV, breaks = c(0, 110, 150), 
                        labels = c("<110 EV Hitters", "110+ EV Hitters")))

#group by 3 EVs instead
max_EV_grouped3 <- batter_all %>%
  group_by(player_name) %>%
  summarize(max_EV = max(launch_speed, na.rm = TRUE)) %>%
  filter(max_EV < 200 & max_EV>0) %>%
  right_join(in_play, by = c("player_name")) %>%
  mutate(EV_group = cut(max_EV, breaks = c(0, 105.99, 111.99, 150), 
                        labels = c("<106 EV Hitters", "106+ EV Hitters", "112+ EV Hitters")))

#graphed divided into 2 EV groups
wOBA_angle_velo_graph_2 <- max_EV_grouped2 %>%
  ggplot(aes(x=launch_angle, y = woba_value, color = EV_group)) +
  geom_smooth(method = "loess", span = .2, se = FALSE)+
  coord_cartesian(ylim=c(0,1), xlim=c(-40,60)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))+
  scale_color_manual(values = c("red", "blue"))+
  theme_bw()+
  theme(legend.title = element_blank())+
  labs(x= "Launch Angle",
       y = "wOBA",
       title = "wOBA by Launch Angle")

#grouped into 3 EV 
wOBA_angle_velo_graph_3 <- max_EV_grouped3 %>%
  ggplot(aes(x=launch_angle, y = woba_value, color = EV_group)) +
  geom_smooth(method = "loess", span = .2, se = FALSE)+
  coord_cartesian(ylim=c(0,1), xlim=c(-40,60)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))+
  scale_color_manual(values = c("black", "orange", "blue"))+
  theme_bw()+
  theme(legend.title = element_blank())+
  labs(x= "Launch Angle",
       y = "wOBA",
       title = "wOBA by Launch Angle")
```

.pull-left[

```{r, echo=FALSE, fig.height=4}
wOBA_angle_velo_graph_2 
```

]
.pull-right[

```{r, echo = FALSE, fig.height=4}
wOBA_angle_velo_graph_3
```


]

---


# Data


---

